import React from 'react';

const wordlist = ["un","deux","trois","quatre","cinq","six","sept","huit","neuf"];

/*
const wordlist = [
    "Une montre",
    "Pêcheur",
    "Écureuil",
    "Baleine",
    "Souris",
    "Hippocampe",
    "Une ruche",
    "Ordinateur",
    "une niche",
    "Mamie",
    "Dinosaure",
    "Pêcher",
    "Limousine",
    "Chevalier",
    "Oeuf de Pâques",
    "Bonhomme de neige",
    "Poireau",
    "Cravate",
    "Robe de mariée",
    "Pyjama",
    "Bague",
    "Varicelle",
    "Lion",
    "Barbe",
    "Pizza",
    "Ciseaux",
    "Trousse",
    "Rouge à lèvres",
    "Écharpe",
    "Chaise",
    "Cadeau",
    "Ballon",
    "Lunettes",
    "Arrosoir",
    "Index",
    "Genou",
    "Domino",
    "Pirate",
    "Magicien",
    "Père Noël",
    "Momie",
    "Cirque",
    "Fourchette",
    "Poubelle",
    "Crocodile",
    "Glace",
    "Coffre-fort",
    "Igloo",
    "Tour Eiffel",
    "Notre Dame",
    "Prise électrique",
    "Calendrier",
    "Cheminée",
    "Chaussette",
    "Jeu de cartes",
    "Pétanque",
    "Autostop",
    "Plombier",
    "Président de la république",
    "Marionnettiste",
    "Berger",
    "Génie",
    "Esthéticienne",
    "Printemps",
    "Artichaut",
    "Pâte à modeler",
    "Farine",
    "Mayonnaise",
    "Twitter",
    "Lampe à huile",
    "Huître",
    "Moule",
    "Chou de bruxelles",
    "Tailleur",
    "Déménager",
    "Ramper",
    "Neveu",
    "Acteur",
    "Ours polaire",
    "Samedi",
    "Halloween",
    "Spéléologie",
    "Perroquet",
    "Éternuer",
    "Judo",
    "Curling",
    "Formule 1",
    "Réalisateur",
    "Mammouth",
    "Fourmilier",
    "Chirurgien",
    "Mannequin",
    "Hockey sur gazon",
    "Oursin",
    "Cachalot",
    "Distributeur",
    "Squash",
    "Accoucher",
    "Sauter à la corde",
    "Faire la vaisselle",
    "Livrer un colis",
    "Jouer du ukulélé",
    "Faire des crèpes",
    "Traire une vache",
    "Manger un hamburger",
    "Lire un livre en braille",
    "Écrire un SMS",
    "Couper du bois",
    "Avoir mal aux dents",
    "Faire une raclette",
    "Sortir le chien",
    "Sauter en parachute",
    "Regarder la télé",
    "Grimper à un arbre",
    "Sauter du plongeoir",
    "Jouer aux lego",
    "Lire dans les lignes de la main",
    "Se laver les dents",
    "Se coiffer les cheveux",
    "Allumer une bougie",
    "Étendre le linge",
    "Tomber amoureux",
    "Jouer au poker",
    "Faire ses devoirs",
    "Cueillir des pommes",
    "Ramasser des champignons",
    "Changer un bébé",
    "Claquer une porte",
    "Avoir une idée",
    "Courir un marathon",
    "Tondre la pelouse",
    "Être en retard",
    "Les doigts dans le nez",
    "Vouloir le beurre et l'argent du beurre",
    "Toucher du bois",
    "Regarder les mouches voler",
    "Pisser dans un violon",
    "Dormir sur ses deux oreilles",
    "Prendre son pied",
    "Poser un lapin",
    "Pleurer à chaudes larmes",
    "Tomber dans les pommes",
    "Un froid de canard",
    "Tourner autour du pot",
    "Avoir plusieurs cordes à son arc",
    "Être la cinquième roue du carrosse",
    "Prendre le taureau par les cornes",
    "Appuyer sur le champignon",
    "Sans queue ni tête",
    "Ne pas avoir les yeux en face des trous",
    "Les bras m'en tombent !",
    "Au pied de la lettre",
    "En avoir par dessus la tête"
];
*/
export function get_wordlist()
{
  return wordlist;
}
